sudo: false

language: node_js

node_js:
  - "6"
  - "5"
  - "4"

install:
  - npm i -g npm@latest
  - npm install

script:
  - npm run coverage

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y p7zip-full

after_script: 'npm run coveralls'
