export const add: () => any
// export const delete: () => any // Variable declaration expected
export const extract: () => any
export const extractFull: () => any
export const hash: () => any
export const list: () => any
export const rename: () => any
export const test: () => any
export const update: () => any
export const listenFactory: () => any
export const listen: () => any
export const mainFactory: () => any
export const main: () => any
